version: "3.4"

services:
  backend:
    image: illfate/smart-purveyance-api:latest # DON'T use latest
    ports:
      - "${BE_PORT}:3000"
    environment:
      - PORT=${BE_PORT}
      - HOST=${BE_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - FOOD_DETECTOR_URI=${FOOD_DETECTOR_URI}
    networks:
      - backend

  food-detector:
    image: vadbeg/food_detector:1.0
    ports:
      - "${FD_PORT}:3000"
    environment:
      - PORT=${FD_PORT}
      - HOST=${FD_HOST}
      - MODEL_PATH=${MODEL_PATH}
      - MODEL_CONFIG_PATH=${MODEL_CONFIG_PATH}
      - CLASS_NAMES_PATH=${CLASS_NAMES_PATH}
      - IMAGE_SIZE=${IMAGE_SIZE}
      - CONF_THRESH=${CONF_THRESH}
      - IOU_THRESH=${IOU_THRESH}
      - AUGMENT=${AUGMENT}
    volumes:
      - /root/backend/data:/data
    networks:
      - backend

networks:
  backend:

volumes:
  data:
