// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Smart-Purveyance-Tracker/backend/api/rest-swagger/models"
)

// CreateProductOKCode is the HTTP code returned for type CreateProductOK
const CreateProductOKCode int = 200

/*CreateProductOK creates product

swagger:response createProductOK
*/
type CreateProductOK struct {

	/*
	  In: Body
	*/
	Payload *models.Product `json:"body,omitempty"`
}

// NewCreateProductOK creates CreateProductOK with default headers values
func NewCreateProductOK() *CreateProductOK {

	return &CreateProductOK{}
}

// WithPayload adds the payload to the create product o k response
func (o *CreateProductOK) WithPayload(payload *models.Product) *CreateProductOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create product o k response
func (o *CreateProductOK) SetPayload(payload *models.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateProductOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateProductDefault error

swagger:response createProductDefault
*/
type CreateProductDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateProductDefault creates CreateProductDefault with default headers values
func NewCreateProductDefault(code int) *CreateProductDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateProductDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create product default response
func (o *CreateProductDefault) WithStatusCode(code int) *CreateProductDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create product default response
func (o *CreateProductDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create product default response
func (o *CreateProductDefault) WithPayload(payload *models.Error) *CreateProductDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create product default response
func (o *CreateProductDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateProductDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
