// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Smart-Purveyance-Tracker/backend/api/rest-swagger/models"
)

// ScanCheckOKCode is the HTTP code returned for type ScanCheckOK
const ScanCheckOKCode int = 200

/*ScanCheckOK scan check o k

swagger:response scanCheckOK
*/
type ScanCheckOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ProductCount `json:"body,omitempty"`
}

// NewScanCheckOK creates ScanCheckOK with default headers values
func NewScanCheckOK() *ScanCheckOK {

	return &ScanCheckOK{}
}

// WithPayload adds the payload to the scan check o k response
func (o *ScanCheckOK) WithPayload(payload []*models.ProductCount) *ScanCheckOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the scan check o k response
func (o *ScanCheckOK) SetPayload(payload []*models.ProductCount) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ScanCheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ProductCount, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ScanCheckDefault error

swagger:response scanCheckDefault
*/
type ScanCheckDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewScanCheckDefault creates ScanCheckDefault with default headers values
func NewScanCheckDefault(code int) *ScanCheckDefault {
	if code <= 0 {
		code = 500
	}

	return &ScanCheckDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the scan check default response
func (o *ScanCheckDefault) WithStatusCode(code int) *ScanCheckDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the scan check default response
func (o *ScanCheckDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the scan check default response
func (o *ScanCheckDefault) WithPayload(payload *models.Error) *ScanCheckDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the scan check default response
func (o *ScanCheckDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ScanCheckDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
