// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ScanProductsHandlerFunc turns a function with the right signature into a scan products handler
type ScanProductsHandlerFunc func(ScanProductsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ScanProductsHandlerFunc) Handle(params ScanProductsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ScanProductsHandler interface for that can handle valid scan products params
type ScanProductsHandler interface {
	Handle(ScanProductsParams, interface{}) middleware.Responder
}

// NewScanProducts creates a new http.Handler for the scan products operation
func NewScanProducts(ctx *middleware.Context, handler ScanProductsHandler) *ScanProducts {
	return &ScanProducts{Context: ctx, Handler: handler}
}

/*ScanProducts swagger:route POST /scanProducts scanProducts

Uploads a file.

*/
type ScanProducts struct {
	Context *middleware.Context
	Handler ScanProductsHandler
}

func (o *ScanProducts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewScanProductsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ScanProductsBody scan products body
//
// swagger:model ScanProductsBody
type ScanProductsBody struct {

	// body
	// Required: true
	Body *string `json:"body"`
}

// Validate validates this scan products body
func (o *ScanProductsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBody(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ScanProductsBody) validateBody(formats strfmt.Registry) error {

	if err := validate.Required("image"+"."+"body", "body", o.Body); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this scan products body based on context it is used
func (o *ScanProductsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ScanProductsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ScanProductsBody) UnmarshalBinary(b []byte) error {
	var res ScanProductsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
