// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Smart-Purveyance-Tracker/backend/api/rest-swagger/models"
)

// ScanProductsOKCode is the HTTP code returned for type ScanProductsOK
const ScanProductsOKCode int = 200

/*ScanProductsOK scan products o k

swagger:response scanProductsOK
*/
type ScanProductsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Product `json:"body,omitempty"`
}

// NewScanProductsOK creates ScanProductsOK with default headers values
func NewScanProductsOK() *ScanProductsOK {

	return &ScanProductsOK{}
}

// WithPayload adds the payload to the scan products o k response
func (o *ScanProductsOK) WithPayload(payload []*models.Product) *ScanProductsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the scan products o k response
func (o *ScanProductsOK) SetPayload(payload []*models.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ScanProductsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Product, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ScanProductsDefault error

swagger:response scanProductsDefault
*/
type ScanProductsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewScanProductsDefault creates ScanProductsDefault with default headers values
func NewScanProductsDefault(code int) *ScanProductsDefault {
	if code <= 0 {
		code = 500
	}

	return &ScanProductsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the scan products default response
func (o *ScanProductsDefault) WithStatusCode(code int) *ScanProductsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the scan products default response
func (o *ScanProductsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the scan products default response
func (o *ScanProductsDefault) WithPayload(payload *models.Error) *ScanProductsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the scan products default response
func (o *ScanProductsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ScanProductsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
