swagger: "2.0"
info:
  title: "test"
  description: "test"
  version: 1.0.0
schemes:
  - http
paths:
  /status:
    get:
      operationId: "getStatus"
      produces:
        - "application/json"
      responses:
        200:
          description: "returns status of server"
          schema:
            properties:
              status:
                type: string
                example: OK
  /signup:
    post:
      operationId: "signup"
      consumes:
        - application/json
      produces:
        - "application/json"
      parameters:
        - name: "user info"
          in: body
          required: true
          schema:
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          headers:
            Authenthication:
              type: string
          description: "returns user"
          schema:
            $ref: '#/definitions/user'
        default:
          description: "error"
          schema:
            $ref: '#/definitions/error'

  /login:
    post:
      operationId: "login"
      consumes:
        - application/json
      produces:
        - "application/json"
      parameters:
        - name: "user info"
          in: body
          required: true
          schema:
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          headers:
            Authenthication:
              type: string
          description: "returns user"
          schema:
            $ref: '#/definitions/user'
        default:
          description: "error"
          schema:
            $ref: '#/definitions/error'

  /scanProducts:
    post:
      operationId: "scanProducts"
      summary: Uploads a file.
      consumes:
        - multipart/form-data
      responses:
        200:
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/productCount'

        default:
          description: "error"
          schema:
            $ref: '#/definitions/error'
      parameters:
        - in: formData
          name: upfile
          type: file
          description: The file to upload.
  /scanCheck:
    post:
      operationId: "scanCheck"
      summary: Uploads a file.
      consumes:
        - multipart/form-data
      responses:
        200:
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/productCount'

        default:
          description: "error"
          schema:
            $ref: '#/definitions/error'
      parameters:
        - in: formData
          name: upfile
          type: file
          description: The file to upload.

definitions:
  user:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
  product:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
  productCount:
    type: object
    properties:
      count:
        type: integer
      product:
        type: object
        $ref: '#/definitions/product'

  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string


