swagger: "2.0"
info:
  title: "test"
  description: "test"
  version: 1.0.0
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
schemes:
  - http
paths:
  /status:
    get:
      operationId: "getStatus"
      produces:
        - "application/json"
      responses:
        200:
          description: "returns status of server"
          schema:
            properties:
              status:
                type: string
                example: OK
  /signup:
    post:
      operationId: "signup"
      consumes:
        - application/json
      produces:
        - "application/json"
      parameters:
        - name: "user info"
          in: body
          required: true
          schema:
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          headers:
            Authenthication:
              type: string
          description: "returns user"
          schema:
            $ref: '#/definitions/user'
        default:
          description: "error"
          schema:
            $ref: '#/definitions/error'

  /login:
    post:
      operationId: "login"
      consumes:
        - application/json
      produces:
        - "application/json"
      parameters:
        - name: "user info"
          in: body
          required: true
          schema:
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          headers:
            Authenthication:
              type: string
          description: "returns user"
          schema:
            $ref: '#/definitions/user'
        default:
          description: "error"
          schema:
            $ref: '#/definitions/error'

  /scanProducts:
    post:
      operationId: "scanProducts"
      summary: Uploads a file.
      security:
        - Bearer: [ ]
      consumes:
        - application/json
      produces:
        - "application/json"

      parameters:
        - in: body
          required: true
          name: "image"
          schema:
            required:
              - body
            properties:
              body:
                type: string
        - in: query
          name: scanDate
          type: string
          format: "date-time"
          description: Date when scan was done
      responses:
        200:
          description: ""
          schema:
            $ref: '#/definitions/scanResponse'
        default:
          description: "error"
          schema:
            $ref: '#/definitions/error'

  /scanCheck:
    post:
      operationId: "scanCheck"
      summary: Uploads a file.
      security:
        - Bearer: [ ]
      consumes:
        - multipart/form-data
      responses:
        200:
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/productCount'

        default:
          description: "error"
          schema:
            $ref: '#/definitions/error'
      parameters:
        - in: formData
          name: upfile
          type: file
          description: The file to upload.
        - in: query
          name: scanDate
          type: string
          format: "date-time"
          description: Date when scan was done

  /product/{productID}:
    parameters:
      - name: productID
        in: path
        type: string
        required: true
    get:
      operationId: "getProduct"
      security:
        - Bearer: [ ]
      parameters:
        - name: productID
          in: path
          type: string
          required: true
      responses:
        200:
          description: "get product"
          schema:
            $ref: '#/definitions/product'
        default:
          description: "error"
          schema:
            $ref: '#/definitions/error'
    post:
      operationId: "createProduct"
      security:
        - Bearer: [ ]
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: product
          required: true
          schema:
            $ref: '#/definitions/product'
          in: body
      responses:
        200:
          description: "creates product"
          schema:
            $ref: '#/definitions/product'
        default:
          description: "error"
          schema:
            $ref: '#/definitions/error'
    put:
      operationId: "updateProduct"
      security:
        - Bearer: [ ]
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: productID
          type: string
          required: true
          in: path
        - name: product
          required: true
          schema:
            $ref: '#/definitions/product'
          in: body
      responses:
        200:
          description: "update product"
          schema:
            $ref: '#/definitions/product'
        default:
          description: "error"
          schema:
            $ref: '#/definitions/error'

  /product/list:
    get:
      operationId: "productList"
      security:
        - Bearer: [ ]
      parameters:
        - in: query
          name: "date"
          type: string
          format: "date"
      responses:
        200:
          description: "returns list of product"
          schema:
            type: array
            items:
              $ref: '#/definitions/product'
        default:
          description: "error"
          schema:
            $ref: '#/definitions/error'
definitions:
  user:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
  product:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      type:
        type: string
      boughtAt:
        type: string
        format: "date-time"
        x-nullable: true
      inStock:
        type: boolean

  productCount:
    type: object
    properties:
      count:
        type: integer
      product:
        type: object
        $ref: '#/definitions/product'

  scanResponse:
    type: object
    properties:
      products:
        type: array
        items:
          $ref: '#/definitions/product'
      productCounts:
        type: array
        items:
          $ref: '#/definitions/productCount'

  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string


