// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductCount product count
//
// swagger:model productCount
type ProductCount struct {
	Product
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ProductCount) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Product
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Product = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ProductCount) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.Product)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this product count
func (m *ProductCount) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this product count based on the context it is used
func (m *ProductCount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Product
	if err := m.Product.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
